/* 10/30/2025

class _BreathingState extends State<BreathingLoopPage> {
  final player = AudioPlayer();

  final bool _inhaleHoldEnabled = true;
  final bool _exhaleHoldEnabled = true;

  void initState() {
    super.initState();

  }

  void runInhale() async {

    await player.setAudioSource(AudioSource.asset('lib/assets/i6.wav')); 
    await player.play();
    // The sound finished.
    print('playing i6.wav');

    runInhaleHold();
    
    }

  void runInhaleHold() async {  

    var counter = 6;
    Timer.periodic(const Duration(seconds: 1), (timer) {
      print(timer.tick);
      counter--;
      if (counter == 0) {
        print('Cancel timer');
        timer.cancel();
      
             runExhale();
      
      }

  });

    }



  void runExhale() async {
      
     await player.setAudioSource(AudioSource.asset('lib/assets/e9.wav'));
      await player.play();
        print('playing e9.wav');

      runExhaleHold();

    }

  void runExhaleHold() async {

    var counter = 6;
    Timer.periodic(const Duration(seconds: 1), (timer) {
      print(timer.tick);
      counter--;
      if (counter == 0) {
        print('Cancel timer');
        timer.cancel();
      
            playBreathingLoop();
      
      }

    });

  }

  void playBreathingLoop() {

    runInhale();
  }

@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(onPressed: () {
            playBreathingLoop();
          }, 
          
          
          
          
          
          
          child: Text('Play'))
        ],
        

              
        )),
    );
  }

}  



 */

/* 10/27/2025

We are changing from to the timer.perodic
      await Future.delayed(Duration(seconds: 6)); 
        print('future.delayed');

 */

/* 10/25/2025

we killed the 
  enum _BreathingCycle { inhale, inhaleHold, exhale, exhaleHold }

and these too

  _BreathingCycle _currentBreath = _BreathingCycle.inhale;
  if (_currentBreath == _BreathingCycle.inhale){
        _currentBreath = _BreathingCycle.inhaleHold;}
    if (_currentBreath == _BreathingCycle.inhaleHold){ 
      _currentBreath = _BreathingCycle.exhaleHold;}

     if (_currentBreath == _BreathingCycle.exhaleHold) {
      _currentBreath = _BreathingCycle.inhale;}


---
This is our breathing loop with one function 
  that uses if else statements to handle the logic

class _BreathingState extends State<BreathingLoopPage> {
  final player = AudioPlayer();
  _BreathingCycle _currentBreath = _BreathingCycle.inhale;

  void initState() {
    super.initState();
    player.playerStateStream.listen((state) {
  if (state.processingState == ProcessingState.completed) {
    // The sound finished. Now what?

    if (_currentBreath == _BreathingCycle.inhale) {
      // The INHALE sound just finished.
      // 1. Change the state to the hold.
      // 2. Start the 6-second hold timer.
      _currentBreath = _BreathingCycle.inhaleHold;
      Future.delayed(Duration(seconds: 6), () {

        print('future.delayed');
      
      player.setAudioSource(AudioSource.asset('lib/assets/e9.wav'));
      
      });
      print('playing e9.wav');
      
    } else if (_currentBreath == _BreathingCycle.inhaleHold) {
      // The EXHALE sound just finished.
      // 1. Change the state to the hold.
      // 2. Start the 6-second hold timer.
      _currentBreath = _BreathingCycle.exhaleHold;
      Future.delayed(Duration(seconds: 6), () {

        print('future.delayed');

      player.setAudioSource(AudioSource.asset('lib/assets/i6.wav'));
      print('playing i6.wav');

      });
    } else if (_currentBreath == _BreathingCycle.exhaleHold) {
      // Move to inhale

      _currentBreath = _BreathingCycle.inhale;
      player.setAudioSource(AudioSource.asset('lib/assets/i6.wav'));
      print('playing i6.wav'); 
    }}});}

  void playBreathingLoop(bool inhaleHoldEnabled) {
    player.setAudioSource(AudioSource.asset('lib/assets/i6.wav')
    );
    player.play();
    //print('playing i6.wav');
  }





 */

/* 10/21/2025 

This is autogenerated that we are working from 

if (_currentBreath == _BreathingCycle.inhale) {
      // Move to inhale hold
      _currentBreath = _BreathingCycle.inhaleHold;
      Future.delayed(Duration(seconds: 6), () {
        playInhaleSequence(true);
      });
    } else if (_currentBreath == _BreathingCycle.inhaleHold) {
      // Move to exhale
      _currentBreath = _BreathingCycle.exhale;
      player.setAudioSource(AudioSource.asset('lib/assets/e6.wav'));
      player.play();
    } else if (_currentBreath == _BreathingCycle.exhale) {
      // Move to exhale hold
      _currentBreath = _BreathingCycle.exhaleHold;
      Future.delayed(Duration(seconds: 6), () {
        playInhaleSequence(true);
      });
    } else if (_currentBreath == _BreathingCycle.exhaleHold) {
      // Move to inhale
      _currentBreath = _BreathingCycle.inhale;
      player.setAudioSource(AudioSource.asset('lib/assets/i6.wav'));
      player.play();
    }




 */

/* 10/16/2025 Original code made with the slow process of autocomplete and gemini


class MyHomePage extends StatelessWidget {
  MyHomePage({super.key});
  final player = AudioPlayer();
  final bool inhaleHoldEnabled = true;
  final bool exhaleHoldEnabled = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Flutter Demo Home Page')),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () async {
                await player.setAudioSource(
                  AudioSource.asset('lib/assets/i6.wav'),
                );
                player.play();

player.playerStateStream.listen((state) {
                  if (state.processingState == ProcessingState.completed) {
                    if (inhaleHoldEnabled) {
                      Future.delayed(Duration(seconds: 6), () async {
                        await player.setAudioSource(
                          AudioSource.asset('lib/assets/e9.wav'),
                        );
                        player.play();
                      });
                    } else {
                      player.setAudioSource(
                        AudioSource.asset('lib/assets/e6.wav'),
                      );
                      player.play();
                    }
                  } else if (state.processingState == ProcessingState.completed && exhaleHoldEnabled) {
                    Future.delayed(Duration(seconds: 6), () async {
                      await player.setAudioSource(
                        AudioSource.asset('lib/assets/i6.wav'),
                      );
                      player.play();
                    });
                  }
                });

                
              },
              child: Text('Play'),
            ),
          ],
        ),
      ),
    );
  }
} 









*/
