
/* This is autogenerated that we are working from

if (_currentBreath == _BreathingCycle.inhale) {
      // Move to inhale hold
      _currentBreath = _BreathingCycle.inhaleHold;
      Future.delayed(Duration(seconds: 6), () {
        playInhaleSequence(true);
      });
    } else if (_currentBreath == _BreathingCycle.inhaleHold) {
      // Move to exhale
      _currentBreath = _BreathingCycle.exhale;
      player.setAudioSource(AudioSource.asset('lib/assets/e6.wav'));
      player.play();
    } else if (_currentBreath == _BreathingCycle.exhale) {
      // Move to exhale hold
      _currentBreath = _BreathingCycle.exhaleHold;
      Future.delayed(Duration(seconds: 6), () {
        playInhaleSequence(true);
      });
    } else if (_currentBreath == _BreathingCycle.exhaleHold) {
      // Move to inhale
      _currentBreath = _BreathingCycle.inhale;
      player.setAudioSource(AudioSource.asset('lib/assets/i6.wav'));
      player.play();
    }




 */















/* 10/16/2025 Original code made with the slow process of autocomplete and gemini


class MyHomePage extends StatelessWidget {
  MyHomePage({super.key});
  final player = AudioPlayer();
  final bool inhaleHoldEnabled = true;
  final bool exhaleHoldEnabled = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Flutter Demo Home Page')),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () async {
                await player.setAudioSource(
                  AudioSource.asset('lib/assets/i6.wav'),
                );
                player.play();

player.playerStateStream.listen((state) {
                  if (state.processingState == ProcessingState.completed) {
                    if (inhaleHoldEnabled) {
                      Future.delayed(Duration(seconds: 6), () async {
                        await player.setAudioSource(
                          AudioSource.asset('lib/assets/e9.wav'),
                        );
                        player.play();
                      });
                    } else {
                      player.setAudioSource(
                        AudioSource.asset('lib/assets/e6.wav'),
                      );
                      player.play();
                    }
                  } else if (state.processingState == ProcessingState.completed && exhaleHoldEnabled) {
                    Future.delayed(Duration(seconds: 6), () async {
                      await player.setAudioSource(
                        AudioSource.asset('lib/assets/i6.wav'),
                      );
                      player.play();
                    });
                  }
                });

                
              },
              child: Text('Play'),
            ),
          ],
        ),
      ),
    );
  }
} 









*/